<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-2KQV9F30" failures="12" tests="129" name="Runner.TestRunner" time="68.111" errors="3" timestamp="2025-06-13T13:08:27 CDT" skipped="0">
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.737"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.379">
    <failure message="expected [400] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at org.testng.Assert.assertEquals(Assert.java:1441)
at StepDefinition.PostNegative_CreateUsers.user_receives_400_bad_request_status_with_appropriate_message(PostNegative_CreateUsers.java:186)
at ✽.User receives 400 Bad Request status with appropriate message(file:///C:/Users/chand/eclipse-workspace/API_RESTASSURED/src/test/resources/Features/Post_Negative.feature:26)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.582"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.418"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.533"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.463"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.380"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.490"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.572"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.391"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.381">
    <failure message="Expected status code 404 but got 400 expected [404] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected status code 404 but got 400 expected [404] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at StepDefinition.Put_UserId.validateStatusCode(Put_UserId.java:90)
at ✽.User should receive status code 404(file:///C:/Users/chand/eclipse-workspace/API_RESTASSURED/src/test/resources/Features/Put_userid.feature:141)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.403"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.368"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.386"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.483"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.765"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.391"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.444"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.297"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.392"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.529"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.470"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.463"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.433"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.393"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.378"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.448">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinition.PostNegative_CreateUsers.user_receives_400_bad_request_status_with_appropriate_message(PostNegative_CreateUsers.java:187)
at ✽.User receives 400 Bad Request status with appropriate message(file:///C:/Users/chand/eclipse-workspace/API_RESTASSURED/src/test/resources/Features/Post_Negative.feature:86)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.918"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="1.131">
    <error message="The step &#039;User receives Content-Type as application/json with status code 201&#039; is undefined.
You can implement this step using the snippet(s) below:

@Then(&quot;User receives Content-Type as application\\/json with status code {int}&quot;)
public void user_receives_content_type_as_application_json_with_status_code(Integer int1) {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}
" type="io.cucumber.testng.UndefinedStepException">
      <![CDATA[io.cucumber.testng.UndefinedStepException: The step 'User receives Content-Type as application/json with status code 201' is undefined.
You can implement this step using the snippet(s) below:

@Then("User receives Content-Type as application\\/json with status code {int}")
public void user_receives_content_type_as_application_json_with_status_code(Integer int1) {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}

at io.cucumber.core.runtime.TestCaseResultObserver.assertTestCasePassed(TestCaseResultObserver.java:69)
at io.cucumber.testng.TestCaseResultObserver.assertTestCasePassed(TestCaseResultObserver.java:23)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:136)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:136)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:136)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:132)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.405"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.417"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.441"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="3.480">
    <failure message="expected [200] but found [404]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at org.testng.Assert.assertEquals(Assert.java:1441)
at StepDefinition.Delete_UserFirstName.user_receives_200_ok_status(Delete_UserFirstName.java:32)
at ✽.User receives 200 OK status with success message(file:///C:/Users/chand/eclipse-workspace/API_RESTASSURED/src/test/resources/Features/Delete_UserFirstname.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.767"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.297"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.396"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.361"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.413"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.553"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.305"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.516"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.416"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="1.669">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinition.Get_Users.validate_user_id_type_integer(Get_Users.java:86)
at ✽.user_id is of integer type with the status code 200 OK(file:///C:/Users/chand/eclipse-workspace/API_RESTASSURED/src/test/resources/Features/get.allusers.feature:21)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.385"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.523">
    <failure message="expected [200] but found [404]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at org.testng.Assert.assertEquals(Assert.java:1441)
at StepDefinition.Delete_UserId.user_receives_200_ok_status(Delete_UserId.java:38)
at ✽.User receives 200 OK status with the success message(file:///C:/Users/chand/eclipse-workspace/API_RESTASSURED/src/test/resources/Features/Delete_Userid.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.627"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.409"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.370"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.382"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.416"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.397"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.382"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.798"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.503">
    <failure message="Expected status code 201 but got 500 expected [201] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected status code 201 but got 500 expected [201] but found [500]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at StepDefinition.PostPositive_CreateUsers.validateResponse(PostPositive_CreateUsers.java:112)
at ✽.User receives 201 Created status(file:///C:/Users/chand/eclipse-workspace/API_RESTASSURED/src/test/resources/Features/post_positive.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.372"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.285"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.460"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.317"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.390"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.369"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.754"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.410">
    <failure message="Expected status code 409 but got 200 expected [409] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected status code 409 but got 200 expected [409] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at StepDefinition.Put_UserId.validateStatusCode(Put_UserId.java:90)
at ✽.User should receive status code 409(file:///C:/Users/chand/eclipse-workspace/API_RESTASSURED/src/test/resources/Features/Put_userid.feature:16)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.482"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.025">
    <error message="JSON object is null. Check the file path or contents." type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: JSON object is null. Check the file path or contents.
at StepDefinition.PostNegative_CreateUsers.sendRequest(PostNegative_CreateUsers.java:193)
at StepDefinition.PostNegative_CreateUsers.sendInvalidLastName(PostNegative_CreateUsers.java:92)
at ✽.User sends the POST request with invalid last name(file:///C:/Users/chand/eclipse-workspace/API_RESTASSURED/src/test/resources/Features/Post_Negative.feature:45)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.507"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.376">
    <failure message="expected [400] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at org.testng.Assert.assertEquals(Assert.java:1441)
at StepDefinition.PostNegative_CreateUsers.user_receives_400_bad_request_status_with_appropriate_message(PostNegative_CreateUsers.java:186)
at ✽.User receives 400 Bad Request status with appropriate message(file:///C:/Users/chand/eclipse-workspace/API_RESTASSURED/src/test/resources/Features/Post_Negative.feature:31)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.391"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.462"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.474"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.462"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.396"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.360"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.293"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.302"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.411"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.406"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.364"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.431"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.335"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.725"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.374"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.398"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.414"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.390"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.441"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.763"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.397"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.364"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.410"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="1.972"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.757"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.013">
    <error message="JSON object is null. Check the file path or contents." type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: JSON object is null. Check the file path or contents.
at StepDefinition.PostNegative_CreateUsers.sendRequest(PostNegative_CreateUsers.java:193)
at StepDefinition.PostNegative_CreateUsers.sendSpecialCharInContact(PostNegative_CreateUsers.java:100)
at ✽.User sends the POST request with special characters in contact number(file:///C:/Users/chand/eclipse-workspace/API_RESTASSURED/src/test/resources/Features/Post_Negative.feature:50)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.352"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.511"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.435"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.414"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.304"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.380"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.840"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.312"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.394"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.361"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.392"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.640"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.443"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.410"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.398"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.408"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="1.815"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.799"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.416"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.443"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.505"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="2.002"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.440"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.469"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.442"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.365"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.386"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.485"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.489"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.404"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.460"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.401"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.408">
    <failure message="Expected status code 409 but got 200 expected [409] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected status code 409 but got 200 expected [409] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at StepDefinition.Put_UserId.validateStatusCode(Put_UserId.java:90)
at ✽.User should receive status code 409(file:///C:/Users/chand/eclipse-workspace/API_RESTASSURED/src/test/resources/Features/Put_userid.feature:26)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.780"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="1.557">
    <failure message="addressId should be a number expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: addressId should be a number expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinition.Get_Users.validate_address_id_type_integer(Get_Users.java:93)
at ✽.address_id is of integer type with the status code 200 OK(file:///C:/Users/chand/eclipse-workspace/API_RESTASSURED/src/test/resources/Features/get.allusers.feature:26)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.278">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinition.Get_Users.validate_404_with_invalid_baseurl(Get_Users.java:142)
at ✽.User receives 404 Not Found status with error message(file:///C:/Users/chand/eclipse-workspace/API_RESTASSURED/src/test/resources/Features/get.allusers.feature:46)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.475"/>
</testsuite> <!-- Runner.TestRunner -->
